import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
// import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import Navbar from '../components/navbar';
import Hero from '../components/sections/hero';

const Home: NextPage = () => (
  <div className='lg:flex mx-auto max-w-screen-xl'>
    <Head>
      <title>Pablo Tor | Developer</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar />
    <main>
      <div id='content' className='overflow-scroll max-h-screen-mobile lg:max-h-screen'>
        <Hero />
        <Hero />
      </div>
    </main>
  </div>
);

export const getStaticProps = async ({ locale }: { locale: string }) => ({
  props: {
    ...(await serverSideTranslations(locale, [
      'common',
      'navbar',
      'hero',
    ])),
  },
});

export default Home;
